- libappstream-builder/plugins/asb-plugin-gettext.c
The gettext MO files can be in either big or little endian format, handle
both types.
> Handle other-endian MO files

- client/as-validate.c
apstream-util → appstream-util
> Fix a typo in command name

- libappstream-glib/as-profile.c
Reference: https://github.com/hughsie/appstream-glib/issues/65
> as_profile: Non-void function should return a value

- libappstream-builder/asb-package-ostree.c
- libappstream-builder/asb-plugin.c
This is some preparation for calling out to appstream-builder from xdg-app.
> Xdg app fixes and changes

- libappstream-glib/as-image.c
- libappstream-glib/as-node-private.h
- libappstream-glib/as-node.c
- libappstream-glib/as-store.c
This is in the DEP-11 spec:
https://www.freedesktop.org/software/appstream/docs/sect-AppStream-DEP11.html#spec-dep11-general
See https://github.com/hughsie/appstream-glib/issues/70
> Implement DEP-11 MediaBaseUrl support

- libappstream-builder/asb-utils.c
This should address issue #101.
> Make archive creation deterministic

- README.md
Adds more clarification for issue discussed as https://github.com/hughsie/appstream-glib/issues/103.
> README.md: add note for glob usage

- libappstream-glib/as-app-desktop.c
AsIcon documents that STOCK icons should have the name set; and that
LOCAL icons should have the filename set. The previous approach to
extracting these properties from as_app_parse_file_key() could sometimes
result in a LOCAL icon with no filename set, if tmp was not an icon name
and not a fallback icon name. Now, we assume that (as long as tmp is not
an absolute path) this means it's an icon name for an icon which is not
installed, and hence the AsIcon type should be STOCK.
Signed-off-by: Philip Withnall <philip.withnall@collabora.co.uk>
> as-app-desktop: Fix association between icon names and types

- data/appdata.its
> its: add <developer_name> to tags extracted for translation

- libappstream-glib/as-app-desktop.c
- meson.build
Various build fixes resulting from trying to build this on a Jessie machine using JHBuild. Because I know how to have fun.
> Meson build fixes

- libappstream-builder/asb-utils.c
- libappstream-glib/as-self-test.c
> A couple of Coverity fixes

- libappstream-glib/as-app-validate.c
> lib/app-validate: Fix typo in variable name

- data/appstream-xml.m4
> Prefer /usr/share/metainfo as default path for metainfo files

- libappstream-builder/plugins/asb-plugin-font.c
I think this should fix #207, and it works for me.  Note however that I don’t know C, so please review carefully.
> Don’t fall back to en if other languages are available.

- libappstream-glib/as-app-validate.c
This changeset makes the image validation code display some descriptive error messages when downloading the image fails. Instead of a simple _"url not found"_ message, the user either gets a _"failed to connect message"_ or an HTTP error code. This should make it easier for users to differentiate between faulty networks, unresponsive or badly configured servers.
The `soup_status_get_phrase()` function is available since `libsoup-2.4`. ([link](https://git.gnome.org/browse/libsoup/tree/libsoup/soup-status.h#n96))
This fixes issue #200.
> Describe connection problems/HTTP errors when validating images

- data/appdata.its
To keep up with https://github.com/ximion/appstream/commits/master/data/its/metainfo.its.
> its: Extract release descriptions and agreement sections for translation

- libappstream-glib/as-node.c
Follow-up on 6048520484101df5d33f3c852c10640e630d20cf
> Escape quotes in attributes

- client/as-compose.c
See https://github.com/flathub/com.adobe.Flash-Player-Projector/issues/2
> Throw an error when a launchable desktop-id is invalid

- libappstream-glib/as-store.c
Previously, as_store_from_file() would either return
G_IO_ERROR_NOT_FOUND or AS_STORE_ERROR_FAILED if the given file did not
exist, depending on its file extension. That is not particularly helpful
for callers.
Instead, guarantee to always return G_IO_ERROR_NOT_FOUND if the file was
not found.
> as-store: Guarantee to return G_IO_ERROR_NOT_FOUND when loading fails

- libappstream-glib/as-enums.c
- libappstream-glib/as-enums.h
Added in AppStream spec:
https://github.com/ximion/appstream/commit/556f01190df1a9158b2532e5ee23a9f2f24ae1f6
> Add support for CONTACT URLs

- client/as-util.c
- libappstream-glib/as-app-builder.c
- libappstream-glib/as-app-desktop.c
- libappstream-glib/as-app-inf.c
- libappstream-glib/as-app-validate.c
- libappstream-glib/as-app.c
- libappstream-glib/as-format.c
- libappstream-glib/as-node.c
- libappstream-glib/as-require.c
- libappstream-glib/as-self-test.c
- libappstream-glib/as-utils.c
- libappstream-glib/meson.build
- meson.build
Signed-off-by: Richard Hughes <richard@hughsie.com>
> Allow building on Windows

- libappstream-glib/as-app-validate.c
- libappstream-glib/as-self-test.c
Fixes some of https://github.com/hughsie/appstream-glib/issues/302
> Do not require <update_contact> for validation unless strict

- libappstream-glib/as-store.c
Added to resolve [GNOME Software not loading YAML](https://gitlab.gnome.org/GNOME/gnome-software/issues/742).
> Support loading YAML from as_store_from_bytes

- libappstream-glib/as-store.c
- libappstream-glib/as-utils.c
Fixes https://github.com/hughsie/appstream-glib/issues/312
> Do not preserve restrictive permissions when installing AppStream files

- README.md
- contrib/ci/Dockerfile-fedora-29
- contrib/libappstream-glib.spec.in
The dependency was removed in f1cdbd834f5baf5db5c7d73849161b186a2d9c54
and 8c58e47632f1e3da2723e57b2cb1bf775da37234. Let's update docs accordingly.
> docs: remove SQLite dependency

- libappstream-glib/as-content-rating.c
- libappstream-glib/as-self-test.c
If an OARS key is missing from a `<content_rating/>` element, the
default value should be `none`, not `unknown`. Change the implementation
of `as_content_rating_get_value()` to do that, and add some tests.
See the OARS specification:
https://github.com/hughsie/oars/blob/master/specification/oars-1.1.md
> as-content-rating: Make default values match OARS semantics

- po/gl.po
Zanata doesn't allow to import po files so, please merge it from this PR
> Update Galician translations

- libappstream-glib/as-app.c
That should fix FTBFS on some architectures
Fixes: #356
> as-app: Properly initialize unique_id_mutex

- README.md
Replace some links in README.md:
* A link http://www.freedesktop.org/wiki/... by https://www.freedesktop.org/wiki/...
* Links http://standards.freedesktop.org/... by https://specifications.freedesktop.org/...
> Replace some links in README.md from http to https

- libappstream-glib/as-self-test.c
- libappstream-glib/as-suggest.c
Fixes https://github.com/hughsie/appstream-glib/issues/396
> Do not show a critical warning on <suggests><id/></suggests>

- libappstream-glib/as-store.c
We are now in version 0.14
Closes #406
Signed-off-by: Corentin Noël <corentin.noel@collabora.com>
> Update current newest version in AsStore

- data/appdata.its
Integrates these commits:
https://github.com/ximion/appstream/commit/e42dd0d071f27d74419b04a52a8388e00777cd88
https://github.com/ximion/appstream/commit/71d134e82752be6f8851c65ba0ce8c312a72214c
https://github.com/ximion/appstream/commit/8c939f999ebf82c3bbf5ad179b24fd7478a0f1d0
https://github.com/ximion/appstream/commit/51ab4f32c56f5cdc293ba0512f003542b83713fc
> its: Sync with appstream

- libappstream-glib/as-app-validate.c
Fixes https://github.com/hughsie/appstream-glib/issues/422
> Fix validation of translated captions when LANG is not C

- client/as-builder.c
- libappstream-builder/asb-app.c
- libappstream-builder/asb-app.h
- libappstream-builder/asb-context.c
- libappstream-builder/asb-context.h
- libappstream-builder/asb-self-test.c
- libappstream-builder/plugins/asb-plugin-appdata.c
- libappstream-builder/plugins/asb-plugin-icon.c
Based on a patch by Fabian Vogt <fvogt@suse.de>, many thanks.
> Remove the --enable-hidpi option completely

- po/LINGUAS
- po/ka.po
> po: add Georgian

- libappstream-glib/as-app-validate.c
- This is a followup on https://github.com/hughsie/appstream-glib/pull/460
- This is issue https://github.com/flathub/org.flatpak.Builder/issues/112
> Tell CURL to follow http redirect for validate

- libappstream-builder/asb-package-rpm.c
- libappstream-builder/asb-self-test.c
- libappstream-builder/plugins/asb-plugin-appdata.c
We're living in an SPDX-only world now.
Fixes https://github.com/hughsie/appstream-glib/issues/478
> Stop trying to convert Fedora licenses into SPDX

- libappstream-glib/as-yaml.c
as per issue #480 this PR adds the application/yaml content type check
https://www.rfc-editor.org/rfc/rfc9512.html
> Support RFC9512 registration for application/yaml Closes #480

- README.md
- contrib/ci/Dockerfile-debian-buster
- contrib/ci/Dockerfile-fedora
- contrib/ci/build_and_test.sh
- contrib/libappstream-glib.spec.in
- libappstream-glib/as-stemmer.c
- libappstream-glib/meson.build
- meson.build
- meson_options.txt
The code is unused now gnome-software is using libappstream.
> Drop support for libstemmer
