hughsie/appstream-glib

libappstream-builder/Makefile.am

Fix Build error in tests
make[3]: Entering directory '/media/src/jhbuild-checkout/source/appstream-glib/libappstream-builder'
CC       asb_self_test-asb-self-test.o
CCLD     asb-self-test
/usr/bin/ld.bfd.real: asb_self_test-asb-self-test.o: undefined reference to symbol 'as_store_from_file'
/opt/gnome/lib/libappstream-glib.so.7: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:885: recipe for target 'asb-self-test' failed
make[3]: *** [asb-self-test] Error 1

tests: Fix DSO Linking error when built with --as-needed

---

configure.ac

If gcab is not installed configure.ac would pass silently. This fixes it so that it enforces the dependency at configure time.

configure.ac: gcab is a hard requirement

---

libappstream-builder/plugins/Makefile.am

Until f630bcf, linking GDKPIXBUF implicitly also linked against gtk+-3.0
libappstream-builder itself is linked against the whole stack, but when linking
using -Wl,--as-needed, the library references to cairo and gdk are dropped for
not being used. Hence, let's explicitly link the font-plugin against GTK.

Build: link libasb_plugin_font.la with GTK3

---

libappstream-glib/as-app-validate.c

Fixes https://github.com/hughsie/appstream-glib/issues/57

Show a better error message when there's not enough text before <ul>

---

libappstream-builder/asb-self-test.c
libappstream-glib/as-cleanup.h
libappstream-glib/as-self-test.c

Switch away from `PATH_MAX` (optional in `POSIX`), so appstream-glib builds and runs fine again on Hurd.

Avoid using PATH_MAX

---

libappstream-builder/asb-self-test.c
libappstream-glib/as-cleanup.h
libappstream-glib/as-self-test.c

glib's g_malloc and friends now always use malloc internally, as of glib
2.46: https://bugzilla.gnome.org/show_bug.cgi?id=751592
This means we no longer have to reallocate glibc malloc'd buffers and
can expect that g_free works fine on them.

Don't reallocate malloc'd memory with g_malloc

---

libappstream-glib/as-app.c

Hi!
I don't have enough time to implement every bit of the DEP-11 0.8 specification (as described at http://www.freedesktop.org/software/appstream/docs/sect-AppStream-DEP11.html ), but this should at least make appstream-glib load some useful data from the files again.
Cheers,
Matthias

dep11: Adapt to spec change

---

data/Makefile.am
data/appdata.its
data/appdata.loc

Recent gettext release has a feature to allow consumer projects to
supply their own string extraction rules for XML files, in ITS format.
Gettext itself ships the rule for AppData, but it would be better
maintained in the upstream project.
See the gettext documentation for details:
http://www.gnu.org/software/gettext/manual/html_node/Preparing-ITS-Rules.html#Preparing-ITS-Rules

Install gettext ITS rules

---

libappstream-glib/as-icon.c

Read the stock icon field.
ASGLib still doesn't support remote and local icons with that, but those aren't used at time, while cached and stock icons are very common.

dep11: Support stock icons

---

libappstream-glib/as-tag.h

Add missing G_BEGIN_DECLS. I suppose it was unintentional?

Add missing G_BEGIN_DECLS in libappstream-glib/as-tag.h.

---

libappstream-glib/as-store.c

Fixes issues when the appstream branch has never been updated in gnome-software.
Also needs this: 
https://cgit.freedesktop.org/xdg-app/xdg-app/commit/?id=c0a18e38c8e97fe79907e98d2dfb94760293e71c

Xdg app dirs

---

libappstream-glib/as-store.c

This was causing system appstream loading to fail and was introduced in
commit 8abd003c.

Fix ordering of parameters to as_store_search_app_info

---

libappstream-glib/as-store.c

It's not uncommon for addons to be called after the functionality they
provide to the application they extend (e.g. "Spell checker").

Addons can have duplcate names

---

libappstream-builder/asb-task.c

Applications depending on yast2 have an implicit dependency
on yast2-branding-openSUSE, which brings required icons in this case.

Add yast2-branding-openSUSE if an app depends on yast2

---

libappstream-builder/asb-utils.c

Looks like the current code used g_ptr_array_sort() incorrectly; fix untested. Noticed because gcc complained:
asb-utils.c: In function ‘asb_utils_write_archive_dir’:
asb-utils.c:538:27: warning: passing argument 2 of ‘g_ptr_array_sort’ from incompatible pointer type [-Wincompatible-pointer-types]
g_ptr_array_sort (files, g_strcmp0);
^~~~~~~~~
In file included from /usr/include/glib-2.0/glib.h:31:0,
from /usr/include/glib-2.0/glib/gprintf.h:21,
from /usr/include/glib-2.0/glib/gstdio.h:23,
from asb-utils.c:30:
/usr/include/glib-2.0/glib/garray.h:175:12: note: expected ‘GCompareFunc {aka int (*)(const void *, const void *)}’ but argument is of type ‘int (*)(const char *, const char *)’
void       g_ptr_array_sort               (GPtrArray        *array,
^~~~~~~~~~~~~~~~

Fix g_ptr_array_sort use

---

libappstream-glib/as-app.c
libappstream-glib/as-app.h

I haven't completed the other side of this patch in GNOME Software but I'm pretty sure this state is the way to go. If you're in agreement it is useful to land this now so G-S etc can depend on a released version that contains the state.

Add an AS_STATE_PURCHASABLE constant so we can support purchasing apps

---

libappstream-builder/asb-utils.c

Correct module name is "gzip".

Correct disabling of timestamps for gzip

---

libappstream-glib/as-environment-ids.txt

Sugar `.appdata.xml` files include Sugar as their `<project_group>`: https://github.com/sugarlabs/sugar-toolkit-gtk3/pull/331/commits/9206c376ace24df6a5814bd9f65f5ca4deec3546#diff-9ecd02401a4ccbfff774b94db38b9c4bR432
So, we probably need to add here as well!

Add Sugar as a valid desktop environment

---

configure.ac
libappstream-glib/appstream-glib.pc.in

pkg-config checks that all declared Requires.private are available
(they are needed for static linking and potentially for their CFLAGS).
---
I'm currently building appstream-glib in an environment where its ability to update x86 firmware is not interesting (we're targeting embedded devices, and secondarily x86 virtual machines) and ran into this issue.

Avoid unsatisfiable development dependency when built without libgcab

---

libappstream-glib/as-utils.c

As 'Public Domain' is not a SPDX-listed license, distributions handle
the string differently. SUSE decided to retain the generic SPDX-Format
used for other licenses, prefixed with SUSE-.

Add SUSE-Public-Domain to License map

---

libappstream-glib/as-yaml.c

The previous commit message blames libyaml for spinning forever on invalid input.  This is not the case.  libyaml is correctly returning an error code, but `as_node_yaml_process_layer` was ignoring it and spinning forever calling back into libyaml as if expecting the error to disappear by itself.
The code should probably be audited for other ignored error codes, but this fixes the immediate problem.

Pay attention to errors from yaml_parser_parse

---

libappstream-glib/as-app-validate.c

When 'as_icon_get_{file}name' return NULL, 'as_app_validate_icons' function
will show Critical Warning by calling 'g_str_has_prefix'. But it wouldn't be
a critical and sometimes, it could be NULL.

as-app-validate: Check if icon_name is NULL

---

client/as-util.c

The current upgrade check just tests to see if the project license is a single SPDX license ID, whereas any license string is valid in this field. For example, Meld has:
`  <project_license>GPL-2.0+ and CC-BY-SA-3.0</project_license>`
which is marked as needing updating.
This patch uses `as_utils_is_spdx_license()`, which seems right to me, but it's not what the actual validation command uses. For some reason, validation manually calls the tokenisation and then validates the licenses individually... I'm not sure if that's more correct in some way I don't recognise, so I went with the easier option.

Make upgrade command check for SPDX license string instead of single ID

---

configure.ac

This allows easier compilation on Ubuntu 16.04

trivial: lower requirement for appstream-glib

---

libappstream-glib/as-yaml.c

It seems this was needed in a second place.  This fixes calling from appstream-util validate.
> $ appstream-util validate ./yaml.yml
> ./yaml.yml: scanner error: mapping values are not allowed in this context at ln:2 col:5

trivial: Use correct autoptr cleanup on yaml error when loading from a file

---

data/appstream-xml.m4

DISTCHECK_CONFIGURE_FLAGS is only for users to override AM_DISTCHECK_CONFIGURE_FLAGS. It's not possible to do if Automake files stomp on that.

Don't recommend use of DISTCHECK_CONFIGURE_FLAGS

---

libappstream-glib/as-store.c

Geary recently renamed its app id to follow flatpak conventions. Adding a fallback to appstream.
For more info, see [bug 766196](https://bugzilla.gnome.org/show_bug.cgi?id=766196) on GNOME bugzilla.

Add Geary to the app id fallbacks

---

libappstream-glib/as-app-validate.c
libappstream-glib/as-self-test.c
libappstream-glib/as-utils.c

SPDX v2.0 and later support an unary "+" operator suffix at the end of
license identifiers, e.g. "CC-BY-SA-3.0+". This commit adds support for
tokenizing and detokenizing this and adds new tests.

Add support for "+" operator at the end of SPDX license identifiers

---

configure.ac

We use C99 features (as-app.c:1278), so need to explicitly enable them
in configure.ac, as some compilers will not enable them automatically,
and will instead error when they encounter usage of C99.
---
This should fix the Jenkins builds on fdo.

build: Enable C99 support in configure.ac

---

libappstream-glib/as-store.c

We can't call methods on the app after we can no longer be sure that
we hold a reference to it.
---
This caused a crash in testing some code based on appstream-glib, in a test that exercises what happens when an AppStream `.xml.gz` file changes. In this particular project not everything in the AppStream is immediately useful (we're looking at a subset), so we don't hold a separate ref on AsApp objects that aren't of interest - I think that's why I saw this but gnome-software wouldn't.

as_store_remove_app_by_id: Don't use-after-free

---

libappstream-glib/as-ref-string.c

AsRefString uses a singleton hash table for deduplicating strings. This
is all "possibly lost" memory according to valgrind as the hash table
never gets destroyed.
This commit adds a custom destructor so that we can clean up the
singleton hash table as well and avoid unnecessary noise in valgrind
output.

Add a destructor for AsRefString

---

libappstream-glib/as-node-private.h
libappstream-glib/as-node.c

As discussed at https://github.com/hughsie/appstream-glib/commit/2557bb9d53590b1926f7f8d36db4296a83395282

as-node: Add back as_node_context_{get,set}_source_kind

---

libappstream-glib/as-self-test.c
libappstream-glib/as-store.c

The hash tables currently reference the keys in the AsApp object, however this
fails in two cases:
1. If you insert two apps with the same ID into the same table the second app
replaces the first but the key is from the original one (confirmed in glib
source code). The first app is unreffed leaving the table to contain an invalid
key (or may occur later if a reference is held elsewhere).
2. There are two tables that contain GPtrArrays of apps. If AsApp in the array
that was used as the key is unreffed then the hash table again contains a freed
key.
I'm assuming these keys weren't copied to save memory, if that is important then
the keys will have to be reference counted or atoms used.

Copy hash table keys from AsApp to avoid them being used after they've been freed

---

data/meson.build
docs/meson.build
meson_options.txt

In some environments generating documentation is unnecessary, or downright impossible.

Conditionally generate docs

---

libappstream-glib/as-app-builder.c

Ok, here's another one!
[On Ubuntu/Debian s390x](https://launchpadlibrarian.net/324218726/buildlog_ubuntu-artful-s390x.appstream-glib_0.7.0~git20170615-1_BUILDING.txt.gz), the test `as_test_app_builder_qt_func` fails.
```
As:ERROR:../libappstream-glib/as-self-test.c:418:as_test_app_builder_qt_func: assertion failed (error == NULL): file /home/ubuntu/appstream-glib-0.7.0~git20170615/data/tests/usr/share/kdeapp/translations/kdeapp_fr.qm is invalid (as-app-error-quark, 0)
```
I spent ages thinking this was an endianness problem, but then I actually looked at the code and it was the `len < sizeof(qm_magic)` that was failing, because `len` is `0`. To be honest I'm not exactly sure why the cast doesn't work, but hey ho - it seems to be not required here.

as-app-builder: Don't cast gsize to guint32 when getting file length

---

libappstream-glib/as-app.c

So that software centres don't present them as removable.
Closes #175

Support CompulsoryForDesktops in YAML

---

libappstream-builder/plugins/meson.build

This fixes the build for appstream-glib on Mageia.
Fixes #179

Have plugins link with asglib along with asbuilder

---

data/meson.build

Accidentally dropped when ported to meson
Fixes: https://github.com/hughsie/appstream-glib/issues/183

meson: Install appdata-xml.m4

---

libappstream-glib/meson.build
meson.build

Commit 081ced436 made the gperf dependency mandatory, but that seems to
have been partially lost in the migration to Meson. If building without
gperf available, Meson configure would succeed, but then build would
fail due to as-tag-private.h not being generated.
Fix that by removing the conditions for gperf in the meson.build files.

build: Make gperf dependency fully required

---

libappstream-glib/as-launchable.c
libappstream-glib/as-launchable.h

This pull request addresses the following issues:
- Appstream-builder throws away the type of launchables that it doesn't understand.  This PR makes it understand the new types from the 0.11 series of he AppStream spec. 
- Launchables don't appear in the appstream-builder output at all since it restricts itself to version 0.8 of the AppStream spec.  This PR makes it output according to version 0.11.4.
- The AppStream version is represented as a double, which has trouble working with anything that has a minor version above 0.9.  This PR switches to strings to represent versions.

Let appstream-builder emit new <launchables> 

---

libappstream-glib/as-image.c

When saving a 16:9 pixbuf and the image parameter is not 16:9 we create
a transparent pixbuf with this ratio and fit the image in it. However,
this calculation was not correctly done due to an integer division so
the result is that the width/height of the pixbuf's area to be copied
was bigger than what the dimensions of the pixbuf; so no image was
copied and we'd be left with a trasnparent pixbuf.
This patch fixes this problem by using multiplications instead of
a division in the mentioned code (as they avoid imprecision problems).

Fix the arithmetic when fitting an image in 16:9

---

contrib/libappstream-glib.spec.in

commit 562772 introduced the usage of pngquant (by calling out to the binary)
and makes use of the --strip parameter, which was introduced in version 2.8 of pngquant.

Trivial: Set minimal required version for pngquant in the sample .spec file

---

libappstream-glib/as-app-desktop.c

Malformed .desktop files might causes crashes because
the returned list is NULL.
I had [this malformed desktop file](https://github.com/hughsie/appstream-glib/files/1656100/org.gnome.frogr.desktop.gz) (See `MimeType`) in my system and this was causing gnome-software to crash all the times when started.
Since `g_key_file_get_string_list` can also return a `NULL` pointer, I think its's safer to do a proper check.

as-app-desktop: don't deference invalid lists

---

libappstream-glib/as-app-desktop.c

Apps that have OnlyShowIn= are equivalent to NoDisplay=True (gnome-shell
doesn't show them). Veto such apps to avoid them inadvertently showing
up in gnome-software and to match gnome-shell behaviour.
https://bugzilla.redhat.com/show_bug.cgi?id=1567689
https://gitlab.gnome.org/GNOME/gnome-software/issues/367

Veto apps that have empty OnlyShowIn=

---

libappstream-glib/as-app.h

This quirk allows apps to marked as having an additional level of checking
performed on the developer. This is to give confidence to the user that this
is the official version of an app. This is a common design pattern used in
modern packaging systems (e.g. Apple App Store, Google Play).

Add AS_APP_QUIRK_DEVELOPER_VERIFIED

---

client/as-util.c

This changeset fixes issue #253.
There's one thing I'm wondering about, though - `matrix-html` can take multiple input.tar.gz arguments, while the `status-*` functions can only take one. Is there any particular reason behind this? Because if not, then I think that also should be changed to make the API more consistent.

Change order of arguments in matrix-html to match status-html

---

libappstream-glib/as-content-rating.c

Also tweak a few bits of punctuation I noticed at the same time.

as-content-rating: fix 'mey' typo

---

libappstream-glib/as-content-rating.c
libappstream-glib/as-content-rating.h
libappstream-glib/as-self-test.c

This allows the set of rating IDs in the AsContentRating to be returned,
allowing the caller to iterate over them to check their values, rather
than having to hard-code their own list of OARS rating IDs.
Includes a basic test.

as-content-rating: Add as_content_rating_get_rating_ids()

---

meson.build

Builder checks for gtk+, but the result isn't used anywhere, thus
introducing an unnecessary gtk+ dependency.
-Dbuilder=true -Dfonts=true would still depend on gdk, but a
-Dbuilder=true -Dfonts=false build doesn't anymore.
Closes: #274

build: Remove unnecessary gtk dependency for builder

---

libappstream-glib/as-self-test.c
libappstream-glib/as-store.c
libappstream-glib/as-store.h

This should fix a number of gnome-software crashes in F29 that usually involve one thread modifying AsStore, and the other one reading back from it.
It's not always that gnome-software spawns two worker threads (this we could fix by adding locking on gnome-software side); sometimes it's the AsStore internal file monitor watch callback firing in the main loop and then changing AsStore from the callback (which runs in a different thread from the plugin loader's worker threads).

Various locking and thread safety fixes for AsStore

---

libappstream-glib/as-store.c

Keep a ref on the AsApp in the worker thread to make sure it doesn't get
destroyed in another thread while being processed.
https://bugzilla.redhat.com/show_bug.cgi?id=1662130
https://bugzilla.redhat.com/show_bug.cgi?id=1661701
https://bugzilla.redhat.com/show_bug.cgi?id=1661382
https://bugzilla.redhat.com/show_bug.cgi?id=1658140
https://bugzilla.redhat.com/show_bug.cgi?id=1644026
https://bugzilla.redhat.com/show_bug.cgi?id=1639558
https://bugzilla.redhat.com/show_bug.cgi?id=1570096

store: Fix threading related crashes when creating the search cache

---

libappstream-glib/meson.build

This fixes cross building of gir using Yocto Project/Buildroot
method.
This is also done on:
atk with -DATK_COMPILATION,
gdk-pixbuf with -DGDK_PIXBUF_COMPILATION,
libgusb with -DGUSB_COMPILATION.

libappstream-glib/meson.build: pass -DAS_COMPILATION to gir compiler

---

libappstream-glib/as-utils.c
libappstream-glib/meson.build

This should help make sure that the version comparison algorithm matches exactly with Fedora's when built on Fedora and supports caret, tilde, and plus characters that all have special semantics in Fedora packages.
https://github.com/hughsie/appstream-glib/issues/270

Use rpmvercmp instead of internal vercmp when built with rpm support

---

contrib/libappstream-glib.spec.in
libappstream-builder/meson.build
libappstream-builder/plugins/meson.build

Nothing uses it, and it's not API or ABI stable.

Do not install the libappstream-builder shared library

---

data/tests/broken.appdata.xml
data/tests/intltool.appdata.xml.in
data/tests/success.appdata.xml
libappstream-glib/as-app-validate.c
libappstream-glib/as-self-test.c

* Require <content_rating> for any desktop or console application
* Make <release> mandatory when validating
* Further relax style requirements
* Require description for desktop an console apps
This changes a lot of things that are now best practice for all apps, and
required to be included in Flathub.
Use `appstream-util validate-relax` to ignore some new failures and use
`appstream-util validate-strict` to bring them back.
Fixes: https://github.com/hughsie/appstream-glib/issues/263

Modernize the validation requirements

---

libappstream-glib/as-app-validate.c

The plan was to require <release> for validate, so that we would be able
to require a version number for flathub, but it accidentally got enabled
for validate-relax as well.

Only require <release> for validate, but not validate-relax

---

libappstream-glib/as-app-validate.c
libappstream-glib/as-self-test.c

Flathub is already patching appstream-glib to remove this check.
Fixes https://github.com/hughsie/appstream-glib/issues/302

Do not require <translation> for validation unless strict

---

libappstream-glib/as-app-validate.c

The timestamp comes from a converted release date but it is in UTC. So anyone
east of UTC will get a "timestamp is in the future" warning for today's date
until UTC ticks past midnight.
According to Wikipedia the highest offset is UTC+14 so let's offset our time
by that much. This way we treat "today" as valid release date anywhere on the
planet.
Fixes https://github.com/hughsie/appstream-glib/issues/317

Offset future checks by UTC+14

---

libappstream-glib/as-app-validate.c

Sometimes it is quite helpful to see the values the validator objects.
Especially when it is hard to comprehend why the validation fails if one has,
say, an image in a stale cache which the validator does not have.

Log expected and actual screenshot dimensions when failing

---

libappstream-glib/as-app-validate.c

This basically updates the list with values from the reference implementation.
https://github.com/hughsie/appstream-glib/blob/d9270c52bffde6ebd4fc3e3b4e0d34f802b920db/libappstream-glib/as-app-validate.c#L1046-L1068
https://github.com/ximion/appstream/blob/08f44a7fda48dc639346414687e79ee2e82963dd/src/as-spdx.c#L469-L507
Fixes hughsie/appstream-glib#323

Update list of allowed metadata licences

---

libappstream-glib/as-app-desktop.c
libappstream-glib/as-app-private.h
libappstream-glib/as-app.c

This fixes showing local apps in GNOME Software without AppStream information.

Allow parsing desktop files using as_app_parse_data()

---

libappstream-glib/as-app.c
libappstream-glib/as-app.h

I think making `as_app_kind_from_string` not return `AS_APP_KIND_UNKNOWN` should be enough, but I'm not really sure since I'm not familiar with how the validation flow works in detail.
See: https://www.freedesktop.org/software/appstream/docs/sect-Metadata-IconTheme.html
Fixes #331

as-app: add "icon-theme" as recognised component type

---

libappstream-glib/as-app.c

We are using it, clearing it, but e never initialize it.
For some reasons it seems to work, not sure how or why,
but when glib is uilt with clang, then the problem
surfaces and we get a nice segmentation fault.
Properly initializing it fixes this

as-app: properly initialize unique_id_mutex

---

meson.build

as-app-desktop.c uses g_key_file_load_from_bytes which was added to glib 2.49.3
(see NEWS¹). Additionally as-format.c uses g_canonicalize_filename which
was added in 2.58 (commit²)
Closes #341.
¹ https://gitlab.gnome.org/GNOME/glib/blob/2.49.3/NEWS#L9
² https://gitlab.gnome.org/GNOME/glib/commit/b9b642de06e714584e89aa7b8d878a98599538ed#c0e40c6287fb64a7a3d8c9fa35b5e014025da233_175_175

Bump minimum glib2 dependency.

---

client/as-util.c

The command validates that an AppData or MetaInfo file includes a release
for the specified version. For forgetful maintainers (hi!), this can be
a useful test during distcheck.

util: Add "validate-version" command

---

data/appstream-util

Commit 5cbcfe05ec missed updating appstream-util's bash completion
for the new command, do that now.

util: Complete new validate-version command

---

README.md

https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps

The AppData files now go to /usr/share/metainfo

---

libappstream-glib/as-node.c
libappstream-glib/as-self-test.c

It segfaulted when building the error message as data_c->name was invalid.
data_c was a valid tag, so only the data_c->tag union member was active.
Fix the crash by calling the proper function instead and add a test case.

Fix crash with invalid children of <ul/>

---

libappstream-glib/as-app-validate.c

KDE team prepares releases for nightly builds far in advance and having the release timestamp in the future is expected. `validate-relax` is being run by `appstream-compose`, thus breaking flatpak-builder builds for them.

Allow timestamp in the future in validate-relax

---

libappstream-glib/as-content-rating.c

This rationalises it with the OARS/CSM mapping of
sex-homosexuality/intense, and with many western societal norms. It is
against the laws and morals of various western countries to discriminate
on sexual orientation, so the mappings for sex-homosexuality/intense and
sex-themes/intense should be the same.
The mappings for the other values of sex-homosexuality and sex-themes
remain different, as their descriptions aren’t as comparable (for
example, for `mild`, the descriptions are “Indirect references to
homosexuality” vs “Provocative references or descriptions”).
The sex-homosexuality ratings category does need to continue to exist,
though, as it’s illegal in some countries to *not* discriminate on
sexual orientation. Those countries can provide and maintain their own
OARS/age mappings. …

as-content-rating: Bump the OARS/CSM mapping of sex-themes/intense

---

libappstream-glib/as-app.c

We managed to merge two MRs to initialize the unique id mutex. Remove
one of the g_mutex_init calls to avoid doing it twice.

as-app: Don't initialize mutex twice

---

README.md
data/tests/broken.appdata.xml
libappstream-glib/as-app-validate.c
libappstream-glib/as-self-test.c

This adds in validation of the <launchable> tags on every validation mode (since the type field of a launchable tag is a required field if launchable is present).
It also adds a dependency to the readme that was missing (the configuration step wouldn't succeed until I installed that).
Fixes #368.

Validate launchable tags

---

libappstream-glib/as-node.c

Avoiding storing identical strings is a clever measure to keep the
appstream file small and clean, but it ignores translation differences
between languages and their specific locales.
Applications tend to "fallback" from missing locales by picking a
translation of the same language but from a different locale.
For instance, when missing a "pt_BR" translation, some apps will
pick the "pt" translation instead. That usually works but there
are some cases when it doesn't, such as for international words:
Brazilian Portuguese (pt_BR) tends to use them, while European
Portuguese (pt) has a translation for everything.
This way, "GNOME Boxes" gets translated to "Caixas GNOME" in
European Portuguese (pt) but the same "GNOME Boxes" name is
expected in Brazilian Portuguese (pt_BR).
This was …

Don't ignore localized strings that are the same as original

---

libappstream-glib/as-content-rating.c

Align the OARS/CSM mappings of sex-homosexuality and sex-themes, as the
two are identical apart from discriminating on sexual orientation.
This is a follow-up to commit 01e9ee8113a8ad.
Signed-off-by: Philip Withnall <pwithnall@endlessos.org>

as-content-rating: Align the OARS/CSM mappings of sex-*

---

client/as-util.c

Markdown underlines are with `=` or `-`, not `~`. This fixes the
Markdown rendering of appdata-to-news-ed files in GitLab.
Signed-off-by: Philip Withnall <pwithnall@endlessos.org>

as-util: Fix Markdown underlining in appdata-to-news

---

libappstream-builder/plugins/asb-plugin-font.c
libappstream-builder/plugins/asb-plugin-icon.c

As per
https://www.freedesktop.org/software/appstream/docs/sect-AppStream-IconCache.html#spec-iconcache-location,
the size of an icon should be specified in its `width` and `height`
attributes, rather than as part of its name.
This was resulting in icons like this in the rpmfusion-free-33 appdata:
```
<icon type="cached" height="128" width="128">128x128/chromium-browser-privacy.png</icon>
```
which were then being resolved to the path:
```
/usr/share/app-info/icons/rpmfusion-free-33/128x128/128x128/chromium-browser-privacy.png
```
which contains a duplicate size subdirectory.
Signed-off-by: Philip Withnall <pwithnall@endlessos.org>

libappstream-builder: Fix paths for cached icons

---

libappstream-builder/asb-utils.c
libappstream-glib/as-icon.c

Ideally only libappstream-builder would be fixed, but
asb_utils_ensure_exists is (transitively) called from builder too, so
fixing also that.
Fixes: #399
Merges: #400

builder: make directories as 0755 && umask

---

libappstream-glib/as-node.c
libappstream-glib/as-self-test.c

Some appstream-data packages add \<em\> and \</em\> or \<code\> and \</code\> to the files.
Not all package manager can handle that. An example would be Pamac from Manjaro

Support em/code tags

---

libappstream-glib/meson.build
meson.build

mingw clang does not support --version-script linker option.

meson: Check --version-script linker option before using.

---

client/as-util.c
libappstream-glib/as-app.c
libappstream-glib/as-node-private.h
libappstream-glib/as-node.c
libappstream-glib/as-self-test.c
libappstream-glib/as-store.c
libappstream-glib/as-store.h

Always store the AppStream metadata version as a string and compare it
like any other version.
This allows to have 0.10 > 0.8 for instance.

Consider AppStream version as a string

---

libappstream-builder/asb-app.c

dbd62f6e05 (#380) removed the WxH directory from the icon filenames, which were also
used as-is for the paths in the icons tarball. However, if width and height
are set on the icon, then it has to be inside a size-specific directory.
With HiDPI enabled, it did even overwrite the non-HiDPI icon it saved just
before because the filenames were the same.
Add the subdirectory back in the resource handling code.
CC @pwithnall
Before:
```
(appstream-builder:18724): Asb-DEBUG: 13:24:10.614: DEBUG:   Saved icon /tmp/tmp.wfYnMaboui/apb/icons/org.qbittorrent.qBittorrent.png
(appstream-builder:18724): Asb-DEBUG: 13:24:10.638: DEBUG:   Saved icon /tmp/tmp.wfYnMaboui/apb/icons/org.qbittorrent.qBittorrent.png
...
<icon type="cached" height="64" width="64">org.qbittorrent.qBittorrent.png</icon>
<icon …
```

libappstream-builder: Fix file paths in icon tarball

---

README.md
client/as-util.c
client/meson.build
contrib/ci/Dockerfile-fedora
contrib/libappstream-glib.spec.in
libappstream-builder/meson.build
libappstream-glib/as-app-validate.c
libappstream-glib/as-utils.c
libappstream-glib/meson.build
meson.build

The former bumped ABI, and all sorts of crazy happens when you link in
libappstream-glib into a process with the 'other' ABI.
It seems the universe has settled on curl as a dep; do the same.

Port from libsoup to libcurl

---

libappstream-glib/as-node.c
libappstream-glib/as-self-test.c

Three commits:
- [Properly initialize is_{em,code}_text fields](https://github.com/hughsie/appstream-glib/commit/9c0b92916dbadc16e66a4b782cfc773a8a041d35)
Fixes: https://github.com/hughsie/appstream-glib/issues/445
- [trivial: Turn is_{em,code}_text fields into bitfields](https://github.com/hughsie/appstream-glib/commit/cbfa4a528c3e6eaee22475a98ee092269cbb0b95)
- [Improve handling of \<em\> and \<code\> tags](https://github.com/hughsie/appstream-glib/commit/bdebc8abfe0dbf5d9d5488af365b291f4b103ed0)
This is still not great code but at least somewhat an improvement. Tests were expanded to showcase the new behavior.
I think, ideally, we would append opening/closing tags to the ancestor `p` or `li` node's cdata as soon as we encounter the start/end of an `em` or `code` element. This would …

Improve handling of <em> and <code> tags

---

libappstream-glib/as-app-validate.c

Oops, trying to use it would just result in criticals.
Fixes #449
NOTE: this is untested: I didn't even attempt to build it. I've provided this because it was requested in #449. Will probably work.

Initialize proxy resolver in appstream-validate

---

client/as-util.c

- This is issue https://github.com/flathub/org.flatpak.Builder/issues/108 and https://github.com/flathub/org.flatpak.Builder/issues/112
Explanation: the switch to curl seems to have missed the fact that by default curl doesn't follow redirects
And flatpak-builder with `--mirror-screenshots-url` did fail when screenshot were hosted (but no only) on github.

Tell CURL to follow http redirect

---

libappstream-builder/plugins/asb-plugin-appdata.c

Consumers of the appdata file are perfectly capable of adding their own default icons, and the specification doesn’t require icons to be present for any of these component types.
If appstream-builder provides a default icon, software centres cannot work out whether it’s provided by the component authors or by appstream-builder. This means software centres cannot override it with their own desktop-specific default icons.
Signed-off-by: Philip Withnall <pwithnall@endlessos.org>
See: https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1483
Fixes: #419

asb-plugin-appdata: Never add default icons to firmware, IMs or codecs

---

libappstream-glib/as-app-validate.c

Screenshot validation includes checking the image size, i.e:
- whether the width isn't too small
- whether the height isn't too small
- whether the width isn't too large
- whether the height isn't too large
Currently, when the first check fails, the error message includes the actual screenshot width. This is not the case for other checks - they do not contain any information about the dimensions. This patch fixes this inconsistency by making all four checks include the relevant information in their error message.

Include screenshot size in all error messages

---

libappstream-builder/plugins/asb-plugin-font.c

https://docs.fileformat.com/font/ttc/
Found in the wild adding appstream data to the sarasa-gothic-font.

asb-plugin-font: Add glob match for .ttc files

---

libappstream-builder/asb-context.c

Fixes https://github.com/hughsie/appstream-glib/issues/482

Do not veto the extension if the parent cannot be found
